### ISSUE TITLE
smooth_dering dependency missing

### ISSUE THREAD

**Issue by Ironclad17** [Irrational-Encoding-Wizardry/vs-dehalo#43]
Installed via pip.
VS Editor Log
`2023-08-01 13:04:42.513
Failed to evaluate the script:
Python exception: ([0;36mexpr_func[0m) There was an error when evaluating the expression:
You might need akarin-plugin, and are missing it. [0;33m(['', '', 'x[-1,-1] x[0,-1] x[1,-1] x[-1,0] x[1,0] x[-1,1] x[0,1] x[1,1] + + + + + + + 4 + 8 / x max'])[0m

Traceback (most recent call last):
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsexprtools\funcs.py", line 47, in expr_func
return core.std.Expr(clips, expr, fmt)
File "src\cython\vapoursynth.pyx", line 2612, in vapoursynth.Function.__call__
vapoursynth.Error: Expr: failed to convert 'x[-1,-1]' to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "E:/Editing/TFL.vpy", line 29, in 
dering = deh.smooth_dering(knlm, contra=1, drrep=24, planes=2)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsdehalo\denoise.py", line 125, in smooth_dering
omask = Morpho.inflate(omask, msmooth, planes)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vstools\types\utils.py", line 176, in _wrapper
return self.function(obj, *args, **kwargs)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsmasktools\morpho.py", line 248, in inflate
src = self._xxflate(True, src, radius, planes, thr, multiply, func=func or self.inflate)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsmasktools\morpho.py", line 222, in _xxflate
return norm_expr(src, expr, planes)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsexprtools\funcs.py", line 109, in norm_expr
return expr_func(clips, tokenized_expr, format, opt, boundary, force_akarin, func)
File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsexprtools\funcs.py", line 49, in expr_func
raise CustomRuntimeError(
[0;31;1mRuntimeError[0m: ([0;36mexpr_func[0m) There was an error when evaluating the expression:
You might need akarin-plugin, and are missing it. [0;33m(['', '', 'x[-1,-1] x[0,-1] x[1,-1] x[-1,0] x[1,0] x[-1,1] x[0,1] x[1,1] + + + + + + + 4 + 8 / x max'])[0m`

**Comment by Setsugennoao** [comment]
Just... install it? https://github.com/AkarinVS/vapoursynth-plugin/releases/tag/v0.96

**Comment by Ironclad17** [comment]
Tried installing versions v0.95 and v0.96g3 to my VS plugins directory and now that causes VSEditor to crash without any error log.

**Comment by Setsugennoao** [comment]
Use vspreview ig
`pip install vspreview`
then `vspreview "E:/Editing/TFL.vpy"`

**Comment by Ironclad17** [comment]
I should clarify this error only occurred with an older video format as source. A .smk file. I just tried other test videos without issue.
`C:\Users\*>vspreview "E:/Editing/TFL.vpy"
2023-08-01 13:46:14.613: matplotlib.font_manager: [1;33mINFO[0m: generated new fontManager
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\Scripts\vspreview.exe\__main__.py", line 7, in <module>
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\init.py", line 124, in main
    main.main_window = MainWindow(Path(os.getcwd()) if args.preserve_cwd else script_path.parent, no_exit)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\core\bases.py", line 29, in __call__
    cls.instance = super().__call__(*args, **kwargs)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\main\window.py", line 197, in __init__
    Plugins(self)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\core\bases.py", line 29, in __call__
    cls.instance = super().__call__(*args, **kwargs)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\plugins\__init__.py", line 121, in __init__
    for plugin in self.file_to_plugins(plugin_file):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\plugins\__init__.py", line 45, in file_to_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\plugins\split_view.ppy", line 3, in <module>
    from vstools import check_variable, split, stack_clips, vs
ImportError: cannot import name 'stack_clips' from 'vstools' (C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vstools\__init__.py)
Exception ignored in atexit callback: <function _dispose at 0x000002561581F490>
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\core\vsenv.py", line 181, in _dispose
    dispose_environment(environment)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\core\vsenv.py", line 150, in dispose_environment
    _finalize_core(env._environment.env_id, id(env.core), True)
TypeError: _finalize_core() takes 2 positional arguments but 3 were given
Exception ignored in: <function ManagedEnvironment.__del__ at 0x000002561581E7A0>
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\vsengine\policy.py", line 348, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down`
